- src/configuration.ts
- test/conformance/configuration.spec.ts
Fixes: #34
Performance test with the current config: .wotanrc.yaml -> wotan:latest -> wotan:recommended
before: 15,5 to 17,0ms
after 12,8 to 14,3ms
That's an improvement of 10 to 20% when there are only a few rules. This will be even more when the config files get bigger.
> Avoid temporary maps while reducing config

- packages/wotan/README.md
- packages/wotan/baselines/rules/no-inferred-empty-object/default/js.js.lint
- packages/wotan/baselines/rules/no-inferred-empty-object/default/test.ts.lint
- packages/wotan/src/rules/no-inferred-empty-object.ts
- packages/wotan/test/rules/no-inferred-empty-object/js.js
- packages/wotan/test/rules/no-inferred-empty-object/test.ts
- packages/wotan/test/rules/no-inferred-empty-object/tsconfig.json
* handle functions and classes from JavaScript files by parsing template tags
* handle merged classes and interfaces
* avoid scanner fallback when signature doesn't match
> no-inferred-empty-object: handle JavaScript declarations

- .circleci/config.yml
- .editorconfig
Use a common base template for test jobs
> Simplify CircleCI config

- packages/ve/baselines/all/nested-script.vue.lint
- packages/ve/baselines/default/nested-script.vue.lint
- packages/ve/custom-typings/void-elements.d.ts
- packages/ve/package.json
- packages/ve/src/index.ts
- packages/ve/tsconfig.json
- yarn.lock
Avoids creating a full AST. Also avoids linting files without top level script tag.
> ve: use sax parser

- README.md
- docs/api.md
Add docs about the current API. I'll try to keep this updated while the API evolves.
The caching part in the last paragraph is not what's currently implemented. PR is on the way.
Requested by @cschulz. Any feedback is very much appreciated.
> Document the basic API usage

- packages/wotan/src/argparse.ts
- packages/wotan/src/commands.ts
- packages/wotan/src/types.ts
- packages/wotan/src/utils.ts
- packages/wotan/test/conformance/argparse.spec.ts
- packages/wotan/test/conformance/commands.spec.ts
Adds a subcommand to create / update / remove the .fimbullinter.yaml file based on your CLI arguments.
> Add save subcommand

- baselines/packages/mimir/test/no-useless-assertion/270-strict/global.ts
- baselines/packages/mimir/test/no-useless-assertion/270-strict/global.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/270-strict/type-assertion.ts
- baselines/packages/mimir/test/no-useless-assertion/270-strict/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts.lint
- packages/mimir/test/no-useless-assertion/270-strict.test.json
- packages/mimir/test/no-useless-assertion/non-null.ts
> no-useless-assertion: update tests for typescript@2.8.0

- scripts/nightly.ts
When publishing nightly releases, update dependencies that were previously published as nightly release.
> nightly: update dependencies on previously published packages

- baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/conditional-types/conditional-types.ts
- baselines/packages/mimir/test/no-useless-assertion/conditional-types/conditional-types.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts.lint
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-useless-assertion/conditional-types.ts
- packages/mimir/test/no-useless-assertion/non-null.ts
> no-useless-assertion: correctly handle conditional types

- baselines/packages/mimir/test/no-useless-spread/default/test.ts
- baselines/packages/mimir/test/no-useless-spread/default/test.ts.lint
- packages/mimir/README.md
- packages/mimir/recommended.yaml
- packages/mimir/src/rules/no-useless-spread.ts
- packages/mimir/test/no-useless-spread/test.ts
* add docs
* add to recommended preset
* add tests with comments
* avoid duplicate errors caused by comments
> no-useless-spread: minor fixes

- packages/wotan/src/project-host.ts
- packages/wotan/test/project/setup/types/foo/index.d.ts
Non-existent files in reference directives can rash project setup as their existence is not checked before the SourceFile is created.
Found this while linting the TypeScript repo.
> Handle nonexistent files during project setup

- packages/mimir/src/rules/prefer-number-isnan.ts
- packages/ymir/src/index.ts
Make this predicate reusable as it will be needed by #181
> add decorator to require a certain library file to be included

- baselines/packages/mimir/test/no-inferred-empty-object/default/test.ts.lint
- baselines/packages/mimir/test/no-inferred-empty-object/pre290/test.ts.lint
- packages/mimir/src/rules/no-inferred-empty-object.ts
- packages/mimir/test/no-inferred-empty-object/test.ts
> no-inferred-empty-object: check tagged templates

- baselines/packages/mimir/test/await-only-promise/default/for-await.ts.fix
- baselines/packages/mimir/test/await-only-promise/default/for-await.ts.lint
- baselines/packages/mimir/test/await-only-promise/pre260/for-await.ts.lint
- packages/mimir/docs/await-only-promise.md
- packages/mimir/src/rules/await-only-promise.ts
- packages/mimir/test/await-only-promise/for-await.ts
> await-only-promise: allow for-await-of with Iterable<PromiseLike<any>>

- baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
- baselines/packages/mimir/test/no-duplicate-spread-property/ts260/test.ts.lint
- packages/mimir/src/rules/no-duplicate-spread-property.ts
Also narrow the error span to the property name.
> no-duplicate-spread-property: improve error messages

- baselines/packages/mimir/test/no-duplicate-case/project-loose/test.ts.lint
- baselines/packages/mimir/test/no-duplicate-case/project/test.ts.lint
- packages/mimir/src/rules/no-duplicate-case.ts
- packages/mimir/test/no-duplicate-case/project-loose.test.json
- packages/mimir/test/no-duplicate-case/test.ts
- packages/mimir/test/no-duplicate-case/tsconfig-loose.json
> no-duplicate-case: handle unions of literal types

- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/non-null.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/non-null.ts.lint
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-useless-assertion/non-null.ts
* correctly handle arrow shorthand return
* inline control flow of IIFEs
> no-useless-assertion: fix detection of use before declare

- baselines/packages/mimir/test/no-nan-compare/default/test.ts.lint
- packages/mimir/src/rules/no-nan-compare.ts
- packages/mimir/test/no-nan-compare/test.ts
> no-nan-compare: also check for Number.NaN

- packages/mimir/test/typecheck/tsconfig-declaration.json
- packages/mimir/test/typecheck/tsconfig.json
> Fix tests for typescript@next

- baselines/packages/mimir/test/no-useless-assertion/post270-loose/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/post270-loose/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/post270-strict/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/pre270-loose/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/pre270-strict/type-assertion.ts.lint
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-useless-assertion/type-assertion.ts
> no-useless-assertion: better handling of contextual type

- .gitignore
- baselines/packages/wotan/test/project/resolvejsonmodule/default/test.ts.lint
- packages/wotan/src/project-host.ts
- packages/wotan/src/runner.ts
- packages/wotan/test/project/resolvejsonmodule/.wotanrc.yaml
- packages/wotan/test/project/resolvejsonmodule/data.json
- packages/wotan/test/project/resolvejsonmodule/default.test.json
- packages/wotan/test/project/resolvejsonmodule/test.ts
- packages/wotan/test/project/resolvejsonmodule/tsconfig.json
> properly support resolveJsonModule compiler option

- baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
- packages/mimir/src/rules/no-useless-predicate.ts
- packages/mimir/test/no-useless-predicate/test.ts
> no-useless-predicate: handle intersection types

- baselines/packages/mimir/test/prefer-for-of/es3/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5-iteration/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es6/types.ts.lint
- packages/mimir/src/rules/prefer-for-of.ts
- packages/mimir/test/prefer-for-of/types.ts
> prefer-for-of: ensure iterated value implements iteration protocol

- baselines/packages/mimir/test/prefer-for-of/es3/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5-iteration/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es6/types.ts.lint
- packages/mimir/src/rules/prefer-for-of.ts
- packages/mimir/test/prefer-for-of/es3.test.json
- packages/mimir/test/prefer-for-of/es5-iteration.test.json
- packages/mimir/test/prefer-for-of/es5.test.json
- packages/mimir/test/prefer-for-of/es6.test.json
- packages/mimir/test/prefer-for-of/jsdoc.js
- packages/mimir/test/prefer-for-of/tsconfig.json
- packages/mimir/test/prefer-for-of/types.ts
> prefer-for-of: handle JSDoc of function parameters

- baselines/packages/mimir/test/no-unstable-api-use/270/test.ts.lint
- baselines/packages/mimir/test/no-unstable-api-use/280/test.ts.lint
- baselines/packages/mimir/test/no-unstable-api-use/default/test.ts.lint
- packages/mimir/src/rules/delete-only-optional-property.ts
- packages/mimir/src/rules/no-unstable-api-use.ts
- packages/mimir/src/utils.ts
- packages/mimir/test/no-unstable-api-use/test.ts
- packages/mimir/test/no-unstable-api-use/tsconfig.json
> no-unstable-api-use: check well-known symbols

- baselines/packages/mimir/test/prefer-dot-notation/default/test.ts.fix
- baselines/packages/mimir/test/prefer-dot-notation/default/test.ts.lint
- packages/mimir/docs/prefer-dot-notation.md
- packages/mimir/src/rules/prefer-dot-notation.ts
- packages/mimir/test/prefer-dot-notation/test.ts
> prefer-dot-notation: parenthesize numeric literals

- baselines/packages/mimir/test/no-inferred-empty-object/290/js.js.lint
- baselines/packages/mimir/test/no-inferred-empty-object/290/jsx.tsx.lint
- baselines/packages/mimir/test/no-inferred-empty-object/290/test.ts.lint
- baselines/packages/mimir/test/no-inferred-empty-object/default/test.ts.lint
- baselines/packages/mimir/test/no-inferred-empty-object/pre290/test.ts.lint
- packages/mimir/src/rules/no-inferred-empty-object.ts
- packages/mimir/test/no-inferred-empty-object/290.test.json
- packages/mimir/test/no-inferred-empty-object/default.test.json
> no-inferred-empty-object: handle recent changes to JSDoc type parameters

- .gitignore
- .travis.yml
- package.json
- scripts/github-release.js
- scripts/last-travis-nightly.js
- yarn.lock
> release: automatic GitHub release

- baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
- baselines/packages/mimir/test/no-duplicate-spread-property/loose/test.ts.lint
- packages/mimir/src/rules/no-duplicate-spread-property.ts
- packages/mimir/test/no-duplicate-spread-property/test.ts
> no-duplicate-spread-property: handle accessor pairs in top level object

- baselines/packages/mimir/test/prefer-for-of/es3/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5-iteration/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es5/types.ts.lint
- baselines/packages/mimir/test/prefer-for-of/es6/types.ts.lint
- packages/mimir/src/rules/prefer-for-of.ts
- packages/mimir/test/prefer-for-of/types.ts
> prefer-for-of: handle private or protected members in iteration protocol

- baselines/packages/mimir/test/no-invalid-assertion/default/union.ts.lint
- packages/mimir/src/rules/no-invalid-assertion.ts
- packages/mimir/test/no-invalid-assertion/union.ts
> no-invalid-assertion: handle intersection types

- baselines/packages/mimir/test/typecheck/composite/typescript.ts.lint
- packages/mimir/src/rules/typecheck.ts
- packages/mimir/test/typecheck/composite.test.json
- packages/mimir/test/typecheck/tsconfig-composite.json
> typecheck: report declaration diagnostics with 'composite' enabled

- packages/wotan/src/services/cached-file-system.ts
- packages/wotan/test/cached-file-system.spec.ts
Also invalidate cache on write or delete.
> Cache directory entries

- package.json
- packages/wotan/src/project-host.ts
- packages/wotan/src/runner.ts
- yarn.lock
> Fixes for breaking API change in TypeScript regarding projectReferences

- CONTRIBUTING.md
Remove Rust mention apparently coming from copy/paste.
> Fix Rust leftover

- baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
- baselines/packages/mimir/test/no-duplicate-spread-property/loose/test.ts.lint
- packages/mimir/src/rules/no-duplicate-spread-property.ts
- packages/mimir/test/no-duplicate-spread-property/test.ts
> no-duplicate-spread-property: handle spread of type variables

- packages/wotan/package.json
- packages/wotan/src/runner.ts
- packages/wotan/src/utils.ts
- packages/wotan/test/runner.spec.ts
- yarn.lock
might be worth moving to a separate package
> normalize glob patterns

- packages/wotan/README.md
> Fix mithotyn link in wotan/README.md

- packages/mimir/test/syntaxcheck/tsconfig.json
- packages/valtyr/README.md
- packages/ve/test/tsconfig.json
- packages/wotan/README.md
- packages/wotan/package.json
- packages/wotan/src/linter.ts
- packages/wotan/test/linter.spec.ts
- packages/wotan/test/processors/vue/tsconfig.json
- yarn.lock
> only use type information in typechecked JS files

- packages/wotan/README.md
- add next line rule disable example
> add next line rule disable example

- baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/pre320/test.ts.lint
- packages/mimir/docs/no-useless-predicate.md
- packages/mimir/src/rules/no-useless-predicate.ts
- packages/mimir/test/no-useless-predicate/test.ts
> no-useless-predicate: check 'in' operator

- baselines/packages/mimir/test/no-useless-predicate/default/bigint.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/pre320/test.ts.lint
- packages/mimir/docs/no-useless-predicate.md
- packages/mimir/src/rules/no-duplicate-case.ts
- packages/mimir/src/rules/no-useless-predicate.ts
- packages/mimir/test/no-useless-predicate/bigint.ts
- packages/mimir/test/no-useless-predicate/test.ts
> no-useless-predicate: check literal comparison

- baselines/packages/mimir/test/no-invalid-assertion/default/literal.ts.lint
- baselines/packages/mimir/test/no-invalid-assertion/pre320/literal.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.lint
- package.json
- packages/mimir/package.json
- packages/mimir/src/rules/no-invalid-assertion.ts
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-invalid-assertion/literal.ts
- packages/mimir/test/no-useless-assertion/type-assertion.ts
- yarn.lock
> exclude 'const' assertions

- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.lint
- packages/mimir/docs/no-useless-assertion.md
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-useless-assertion/type-assertion.ts
> no-useless-assertion: detect redundant 'const' assertion

- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/300-strict/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.lint
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.fix
- baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.lint
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/test/no-useless-assertion/type-assertion.ts
> no-useless-assertion: check literal assertion in const context

- package.json
- tsconfig.build.json
- yarn.lock
> Use transform to downlevel readonly array types

- docs/testing-rules.md
- docs/writing-rules.md
Adds documentation about testing rules. Part of #17 
@CSchulz you might be interested in this. Could you please read through this and leave some comments if anything is unclear?
> docs: how to test rules

- .vscode/extensions.json
- packages/mithotyn/README.md
- packages/wotan/README.md
> docs: mention official VSCode plugin

- packages/bifrost/src/index.ts
- packages/bifrost/test/formatter.spec.ts
> bifrost: pass fileNames to TSLint formatters

- baselines/packages/wotan/api/src/fix.d.ts
- baselines/packages/wotan/api/src/linter.d.ts
- baselines/packages/wotan/api/src/services/configuration-manager.d.ts
- baselines/packages/ymir/api/src/index.d.ts
- scripts/api-guard.ts
- tsconfig-base.json
> build: no longer strip comments

- packages/mimir/test/await-only-promise/default.test.json
- packages/mimir/test/no-duplicate-case/default.test.json
- packages/mimir/test/no-duplicate-case/project.test.json
- packages/mimir/test/no-duplicate-spread-property/js-literal.test.json
- packages/mimir/test/no-inferred-empty-object/default.test.json
- packages/mimir/test/no-inferred-empty-object/pre330.test.json
- packages/mimir/test/no-invalid-assertion/default.test.json
- packages/mimir/test/no-unstable-api-use/default.test.json
- packages/mimir/test/no-useless-assertion/conditional-types.test.json
- packages/mimir/test/no-useless-assertion/definite-assignment-loose.test.json
- packages/mimir/test/no-useless-assertion/definite-assignment-strict.test.json
- packages/mimir/test/no-useless-assertion/strict.test.json
- packages/mimir/test/no-useless-predicate/default.test.json
- packages/mimir/test/typecheck/composite.test.json
- packages/mimir/test/typecheck/default.test.json
- packages/wotan/test/project/references/default.test.json
- packages/wotan/test/project/references/references.test.json
- packages/wotan/test/project/resolvejsonmodule/default.test.json
- scripts/cleanup-tests.ts
> cleanup-tests: simplify version range

- packages/wotan/src/services/default/file-filter.ts
- packages/wotan/src/utils.ts
> file-filter: extract and simplify handling of project references

- packages/wotan/src/project-host.ts
> Cache module resolutions when applying fixes to Program

- baselines/packages/mimir/test/no-useless-initializer/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.fix
- baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.lint
- baselines/packages/mimir/test/no-useless-initializer/project-pre350/test.ts.fix
- baselines/packages/mimir/test/no-useless-initializer/project-pre350/test.ts.lint
- baselines/packages/mimir/test/no-useless-initializer/project/test.ts.fix
- packages/mimir/src/rules/no-useless-initializer.ts
- packages/mimir/test/no-useless-initializer/project-pre350.test.json
- packages/mimir/test/no-useless-initializer/project.test.json
- packages/mimir/test/no-useless-initializer/test.ts
> no-useless-initializer: destructuring with computed name and array destructuring

- packages/wotan/package.json
- packages/wotan/src/runner.ts
- packages/wotan/test/runner.spec.ts
- yarn.lock
> handle absolute windows paths

- baselines/packages/mimir/test/no-return-await/default/test.ts.fix
- baselines/packages/mimir/test/no-return-await/default/test.ts.lint
- baselines/packages/mimir/test/no-unstable-api-use/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
- baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
- packages/mimir/src/rules/no-return-await.ts
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/src/rules/no-useless-predicate.ts
- packages/mimir/test/no-return-await/test.ts
- packages/mimir/test/no-unstable-api-use/test.ts
- packages/mimir/test/no-useless-predicate/test.ts
> handle nullish coalescing and private identifiers

- baselines/packages/wotan/test/project/references/filtered/a/a.ts.lint
- baselines/packages/wotan/test/project/references/filtered/a/a1.js.lint
- baselines/packages/wotan/test/project/references/references/a/a.ts.fix
- baselines/packages/wotan/test/project/references/references/a/a.ts.lint
- baselines/packages/wotan/test/project/references/references/a/a1.js.lint
- packages/wotan/src/services/default/file-filter.ts
- packages/wotan/src/utils.ts
- packages/wotan/test/project/references/a/a.ts
- packages/wotan/test/project/references/a/a1.js
- packages/wotan/test/project/references/a/data.json
- packages/wotan/test/project/references/a/tsconfig.json
- packages/wotan/test/project/references/out-a/a.js
- packages/wotan/test/project/references/out-a/a1.js
- packages/wotan/test/project/references/out-a/data.json
- packages/wotan/test/project/references/out-a/index.js
- packages/wotan/test/project/references/out-a/tsconfig.json
- packages/wotan/test/project/references/outdir/a/a.d.ts
- packages/wotan/test/project/references/outdir/a/a1.d.ts
> file-filter: handle JSON and JS(X) files in composite projects

- baselines/packages/mimir/api/packlist.txt
- baselines/packages/mimir/api/src/rules/no-writeonly-property-read.d.ts
- baselines/packages/mimir/test/no-writeonly-property-read/default/assignment-declaration.js.lint
- baselines/packages/mimir/test/no-writeonly-property-read/default/test.ts.lint
- packages/mimir/README.md
- packages/mimir/docs/no-restricted-property-access.md
- packages/mimir/docs/no-useless-predicate.md
- packages/mimir/docs/no-writeonly-property-read.md
- packages/mimir/recommended.yaml
- packages/mimir/src/rules/no-duplicate-case.ts
- packages/mimir/src/rules/no-invalid-assertion.ts
- packages/mimir/src/rules/no-unstable-api-use.ts
- packages/mimir/src/rules/no-useless-assertion.ts
- packages/mimir/src/rules/no-useless-initializer.ts
- packages/mimir/src/rules/no-useless-predicate.ts
- packages/mimir/src/rules/no-writeonly-property-read.ts
- packages/mimir/src/rules/prefer-for-of.ts
- packages/mimir/src/rules/prefer-number-methods.ts
- packages/mimir/src/utils.ts
- packages/mimir/test/no-writeonly-property-read/.wotanrc.yaml
- packages/mimir/test/no-writeonly-property-read/assignment-declaration.js
- packages/mimir/test/no-writeonly-property-read/default.test.json
- packages/mimir/test/no-writeonly-property-read/test.ts
- packages/mimir/test/no-writeonly-property-read/tsconfig.json
> new rule: no-writeonly-property-read

- .dependency-cruiser.json
- baselines/packages/wotan/api/language-service/index.d.ts
- packages/mithotyn/index.ts
- packages/wotan/language-service/index.ts
> LS plugin: better caching and logging
