fimbullinter/wotan

.circleci/config.yml
.codecov.yml
README.md
appveyor.yml
package.json
yarn.lock

Coveralls has pretty bad delays recently.
Codecov allows merging coverage per commit, instead of per build on coveralls. That allows reporting coverage from all CircleCI containers as well as AppVeyor to get a more complete coverage report.

Use codecov.io instead of Coveralls

---

.gitignore
.travis.yml
package.json
packages/bifrost/src/index.ts
packages/wotan/src/services/line-switches.ts
scripts/nightly.ts
scripts/tsconfig.json

The script get's the diff since the last relase (stable or nightly). It updates and publishes all packages that were changed or that depend (also transitively) on a changed package excluding private packages.

Publish nightly versions using Travis CI

---

package.json
packages/bifrost/src/index.ts
scripts/nightly.ts
scripts/release.ts
scripts/tslint.json
scripts/util.ts
yarn.lock

Refactor nightly release script to extract some common functions.
Add release script for minor and major versions. Dependencies in package.json are automatically updated.
The version in the root package.json is used as the new version of all changed packages. All packages are released if this is a major release.
The root package.json's version is then updated to the next minor version (for nightlies).

Add release script for minor and major releases

---

packages/bifrost/src/index.ts
packages/bifrost/test/rule.spec.ts

This change enforces all TSLint rule failures to belong to the same SourceFile as the one currently linted.
The only rules package that would violate that restriction is Codelyzer AFAICT.

bifrost: enforce failures for the same file only

---

packages/wotan/package.json
packages/wotan/src/runner.ts
packages/wotan/test/conformance/runner.spec.ts
packages/wotan/test/integration/processors/prefixed/project.test.json
yarn.lock

Fix a bug where non-magic patterns were not matched against the original name of a processed file when linting with `--project`.
Also drop to-absolute-glob dependency and show relative pattern in error message.

Fix pattern matching in processed Program

---

docs/api.md
packages/valtyr/README.md
packages/valtyr/package.json
packages/valtyr/src/configuration-provider.ts
packages/valtyr/test/configuration-provider.spec.ts
packages/valtyr/test/fixtures/.fimbullinter.yaml
packages/valtyr/test/fixtures/processed.vue
packages/valtyr/test/module.spec.ts
packages/wotan/src/commands.ts
packages/wotan/src/di/core.module.ts
packages/wotan/src/di/default.module.ts
packages/wotan/src/project-host.ts
packages/wotan/test/conformance/commands.spec.ts
packages/wotan/test/conformance/configuration.spec.ts
packages/wotan/test/conformance/runner.spec.ts

Allows configuring processors for Valtýr in `.fimbullinter.yaml`

Add processor support to Valtýr

---

baselines/packages/wotan/test/rules/prefer-number-isnan/es5/declaration.d.ts.lint
baselines/packages/wotan/test/rules/prefer-number-isnan/es5/test.ts.lint
baselines/packages/wotan/test/rules/prefer-number-isnan/esnext/declaration.d.ts.lint
baselines/packages/wotan/test/rules/prefer-number-isnan/esnext/test.ts
baselines/packages/wotan/test/rules/prefer-number-isnan/esnext/test.ts.lint
packages/wotan/README.md
packages/wotan/configs/recommended.yaml
packages/wotan/src/argparse.ts
packages/wotan/src/rules/prefer-number-isnan.ts
packages/wotan/test/rules/prefer-number-isnan/.wotanrc.yaml
packages/wotan/test/rules/prefer-number-isnan/declaration.d.ts
packages/wotan/test/rules/prefer-number-isnan/es5.test.json
packages/wotan/test/rules/prefer-number-isnan/esnext.test.json
packages/wotan/test/rules/prefer-number-isnan/test.ts
packages/wotan/test/rules/prefer-number-isnan/tsconfig.es5.json
packages/wotan/test/rules/prefer-number-isnan/tsconfig.esnext.json

This rule needs the TypeChecker to determine if `lib.es2015.core.d.ts` is available, because that's where `Number.isNaN` is declared (in the typical case).
Custom libraries and global augmentations are currently not supported.

add new rule: prefer-number-isnan

---

packages/wotan/src/runner.ts
packages/wotan/test/runner.spec.ts

This ensures you can use an older version of typescript for linting, even if the tsconfig contains settings for newer typescript versions.

report errors in tsconfig.json as warnings

---

baselines/packages/mimir/test/no-misused-generics/default/test.ts.lint
packages/mimir/README.md
packages/mimir/src/rules/no-misused-generics.ts
packages/mimir/test/no-misused-generics/test.ts

Benefits:
* signatures without TypeParameters are faster to typecheck
* less useless code
* added type safety:
```ts
declare function bad<T extends {prop: string}>(param: T): void;
bad({prop: '', prop2: 2}); // no excess property error
// refactor to
declare function good(param: {prop: string}): void;
good({prop: '', prop2: 2}); // now there is an excess property error
```

no-misused-generics: detect type parameters that actually mean any

---

baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
packages/mimir/src/rules/no-useless-predicate.ts
packages/mimir/test/no-useless-predicate/test.ts

Only check literal types. Checking unions of literals seems not to be worth the effort.

no-useless-predicate: check literal types

---

packages/valtyr/src/formatter-loader.ts
packages/valtyr/test/formatter-loader.spec.ts

Previously using custom formatters by relative path was not possible.

valtyr: correctly load custom formatters

---

baselines/packages/mimir/test/await-async-result/default/test.ts.lint
packages/mimir/src/rules/await-async-result.ts
packages/mimir/src/rules/no-unused-label.ts
packages/mimir/src/rules/try-catch-return-await.ts
packages/mimir/src/utils.ts
packages/mimir/test/await-async-result/test.ts

Simplify and optimize `no-unused-label` and `await-async-result`.

Extract logic to visit child statements

---

baselines/packages/mimir/test/no-useless-spread/default/test.ts
baselines/packages/mimir/test/no-useless-spread/default/test.ts.lint
packages/mimir/src/rules/no-useless-spread.ts
packages/mimir/test/no-useless-spread/test.ts

Don't fix object spread at all to avoid creating duplicate key errors.
Added a test case for duplicate object keys. Maybe someone wants to fix this later.

no-useless-spread: don't fix object spread

---

baselines/packages/mimir/test/no-inferred-empty-object/default/test.ts.lint
packages/mimir/src/rules/no-inferred-empty-object.ts
packages/mimir/test/no-inferred-empty-object/test.ts

If the constructor has no type parameters, look on the class declaration.
The change in `getTypeParameters` might also address #194

no-inferred-empty-object: correctly check classes with constructor

---

baselines/packages/mimir/test/no-useless-assertion/definite-assignment-strict/definite-assignment.ts
baselines/packages/mimir/test/no-useless-assertion/definite-assignment-strict/definite-assignment.ts.lint
packages/mimir/src/rules/no-useless-assertion.ts

The compiler only checks properties whose names are identifiers.

no-useless-assertion: forbid definite assignment assertion on computed name

---

baselines/packages/mimir/test/await-only-promise/default/test.ts.fix
baselines/packages/mimir/test/await-only-promise/default/test.ts.lint
baselines/packages/mimir/test/await-only-promise/pre260/test.ts.lint
baselines/packages/mimir/test/no-return-await/default/test.ts.fix
baselines/packages/mimir/test/no-return-await/default/test.ts.lint
baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts.fix
baselines/packages/mimir/test/no-useless-assertion/270-strict/non-null.ts.lint
baselines/packages/mimir/test/no-useless-assertion/270-strict/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/270-strict/type-assertion.ts.lint
baselines/packages/mimir/test/no-useless-assertion/post270-loose/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/post270-loose/type-assertion.ts.lint
baselines/packages/mimir/test/no-useless-assertion/post270-strict/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/post270-strict/type-assertion.ts.lint
baselines/packages/mimir/test/no-useless-assertion/pre270-loose/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/pre270-loose/type-assertion.ts.lint
baselines/packages/mimir/test/no-useless-assertion/pre270-strict/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/pre270-strict/type-assertion.ts.lint
baselines/packages/mimir/test/prefer-object-spread/default/test.ts.fix
baselines/packages/mimir/test/prefer-object-spread/default/test.ts.lint
packages/mimir/src/rules/await-only-promise.ts
packages/mimir/src/rules/no-return-await.ts
packages/mimir/src/rules/no-useless-assertion.ts
packages/mimir/src/rules/prefer-object-spread.ts
packages/mimir/src/utils.ts
packages/mimir/test/await-only-promise/test.ts
packages/mimir/test/no-return-await/test.ts
packages/mimir/test/no-useless-assertion/type-assertion.ts
packages/mimir/test/prefer-object-spread/test.ts

Also checks nested expressions that would cause parsing ambiguity. Prevent class and function expressions from being parsed as declaration statement.
* await-only-promise, fixes: #202
* no-return-await
* no-useless-assertion, fixes: #250
* prefer-object-spread

add parens in autofixer if necessary

---

baselines/packages/mimir/test/type-assertion/classic/test.ts.fix
baselines/packages/mimir/test/type-assertion/classic/test.ts.lint
baselines/packages/mimir/test/type-assertion/default/test.ts.fix
baselines/packages/mimir/test/type-assertion/default/test.ts.lint
packages/mimir/src/rules/type-assertion.ts
packages/mimir/test/type-assertion/test.ts

* avoid parse error in exponentiation operator: `<T>1 ** 2` is not allowed, use `(<T>1) ** 2` instead
* avoid changing semantics of binary expressions

type-assertion: handle binary expressions with classic type assertion

---

baselines/packages/mimir/test/no-useless-initializer/default/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/default/test.ts.lint
baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.lint
baselines/packages/mimir/test/no-useless-initializer/project/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/project/test.ts.lint
packages/mimir/src/rules/no-unstable-api-use.ts
packages/mimir/src/rules/no-useless-initializer.ts
packages/mimir/src/utils.ts
packages/mimir/test/no-useless-initializer/test.ts

Fail if the computed name
* only consists of string or number literal types
* each type has a symbol
* symbol is not optional or includes `undefined` in its type

no-useless-initializer: check computed name in binding pattern

---

baselines/packages/mimir/test/no-unstable-api-use/270/jsx.tsx.lint
baselines/packages/mimir/test/no-unstable-api-use/270/test.ts.lint
baselines/packages/mimir/test/no-unstable-api-use/280/jsx.tsx.lint
baselines/packages/mimir/test/no-unstable-api-use/280/test.ts.lint
baselines/packages/mimir/test/no-unstable-api-use/default/jsx.tsx.lint
baselines/packages/mimir/test/no-unstable-api-use/default/test.ts.lint
packages/mimir/src/rules/no-unstable-api-use.ts
packages/mimir/test/no-unstable-api-use/test.ts

This follows the same approach as TypeScript's signature help: if the expression is an Identifier, use that name, for PropertyAccessExpression use the property name, otherwise show no name at all.

no-unstable-api-use: better error message for signatures

---

baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
baselines/packages/mimir/test/no-duplicate-spread-property/loose/test.ts.lint
packages/mimir/src/rules/no-duplicate-spread-property.ts
packages/mimir/test/no-duplicate-spread-property/test.ts

no-duplicate-spread-property: exclude class Getters and Setters

---

packages/wotan/README.md

[Wotan README](https://github.com/fimbullinter/wotan/blob/master/packages/wotan/README.md#cli-options) says,
> -e --exclude <glob> excludes all files that match the given glob pattern from linting. This option can be used multiple times to specify multiple patterns. For example -e '**/*.js' -e '**/*.d.ts'. It is recommended to wrap the glob patterns in single quotes to prevent the shell from expanding them.
...and while all other examples in the doc use single quote, the example in the Quick Start section uses double quote, which can be thought as a reference.

Wotan README recommends single quote, but Quick Start uses double quote.

---

.circleci/config.yml
packages/wotan/src/project-host.ts
packages/wotan/src/runner.ts
packages/wotan/src/services/default/file-system.ts
packages/wotan/test/commands.spec.ts

This ensures tests (and or course the application) work as expected on case sensitive file systems with mixed case paths.

CI: test mixed case paths on case sensitive file system

---

packages/wotan/src/project-host.ts
packages/wotan/src/services/cached-file-system.ts
packages/wotan/src/services/default/file-system.ts
packages/wotan/test/cached-file-system.spec.ts
packages/ymir/src/index.ts

This uses the new Node.js option `{withFileTypes: true}` if available to avoid useless file system calls.
It caches the kind if provided and needs to look up the real type for symlinks.
Caching of directory entries will be done in a separate PR.

Allow FileSystem.readDirectory to return Array<string|Dirent>

---

docs/writing-rules.md
packages/wotan/package.json
packages/wotan/src/fix.ts
packages/wotan/test/fix.spec.ts
yarn.lock

Encountered this while working on #434 
We now trust the developer of the rule that adjacent replacements of a fix are intended to be applied this way. This requires a stable sorting algorithm as `Array.prorotype.sort` is not deterministic and might shuffle entries with the same sort value.

fixer: merge adjacent insertion replacements of a single fix

---

package.json
packages/wotan/package.json
packages/wotan/src/services/default/file-system.ts
yarn.lock

Uses the newly added `recursive` option of `fs.mkdir(Sync)` if available. It falls back to the old behavior of creating parent directories one at a time.

FileSystem: use recursive mkdirSync if available

---

baselines/packages/mimir/test/no-useless-initializer/default/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/default/test.ts.lint
baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/project-loose/test.ts.lint
baselines/packages/mimir/test/no-useless-initializer/project/test.ts.fix
baselines/packages/mimir/test/no-useless-initializer/project/test.ts.lint
packages/mimir/src/rules/no-useless-initializer.ts
packages/mimir/test/no-useless-initializer/test.ts

no-useless-initializer: bugfix for destructuring when property is type variable

---

baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
baselines/packages/mimir/test/no-duplicate-spread-property/loose/test.ts.lint
packages/mimir/src/rules/no-duplicate-spread-property.ts
packages/mimir/test/no-duplicate-spread-property/test.ts

no-duplicate-spread-property: handle intersection types

---

baselines/packages/mimir/test/async-function-assignability/default/test.ts.lint
packages/mimir/src/rules/async-function-assignability.ts
packages/mimir/test/async-function-assignability/test.ts

* handle computed names
* include property or method name in message text.
* handle overload signatures separately
* remove `| undefined` before looking for call signatures

async-function-assignability: handle computed property names

---

package.json
tsconfig.build.json
yarn.lock

Uses `ttypescript` and `ts-transform-const-enum` to preserve exported const enums in emitted JS code and removes the `const` modifier from declaration files.
Fixes: #404
`tsutils@3.5.2` uses the same build tools so that its declaration files are safe to consume.

avoid const enum in declaration files

---

packages/heimdall/src/index.ts
packages/heimdall/test/formatter-loader.spec.ts
packages/heimdall/test/rule-loader.spec.ts
packages/valtyr/src/configuration-provider.ts
packages/wotan/src/services/configuration-manager.ts
packages/wotan/src/services/default/builtin-resolver.ts
packages/wotan/src/services/default/configuration-provider.ts
packages/wotan/src/services/default/formatter-loader-host.ts
packages/wotan/src/services/default/resolver.ts
packages/wotan/src/services/default/rule-loader-host.ts
packages/wotan/src/services/processor-loader.ts
packages/wotan/test/configuration.spec.ts
packages/wotan/test/services.spec.ts
packages/ymir/src/index.ts

Move all uses of `require` to `NodeResolver`. This allows for easy substitution by only providing one different service.
It also removes code that relied on Node's module not found errors.

avoid uses of require where possible

---

packages/mithotyn/README.md
packages/wotan/language-service/index.ts
packages/wotan/src/services/configuration-manager.ts

Look up `.fimbullinter.yaml` and use `modules`, `config`, `files` and `exclude` if present

LanguageService plugin: load global options from .fimbullinter.yaml

---

packages/valtyr/test/fixtures/processed2.vue
packages/valtyr/test/fixtures/processed3.vue
packages/valtyr/test/module.spec.ts
packages/ve/src/index.ts

Don't include the line break following the opening tag in the linted source code.
Also fixes an outstanding TODO to adjust the character offset if there is no line break after the opening tag

ve: trim off leading line break

---

packages/valtyr/src/configuration-provider.ts
packages/valtyr/test/configuration-provider.spec.ts
packages/wotan/README.md
packages/wotan/src/services/configuration-manager.ts

Changes glob patterns in `processor.files` and `exclude` to match dotfiles by default.

configuration: patterns match dotfiles

---

baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
baselines/packages/mimir/test/no-useless-predicate/loose/test.ts.lint
baselines/packages/mimir/test/no-useless-predicate/pre320/test.ts.lint
packages/mimir/docs/no-useless-predicate.md
packages/mimir/src/rules/no-useless-predicate.ts
packages/mimir/test/no-useless-predicate/test.ts
packages/mimir/test/no-useless-predicate/tsconfig.json

If a property access or element access matches an index signature, treat the resulting type as optional (i.e. include `undefined`).
If there are known properties in addition to the index signature, the type is not optional if every accessed property has a corresponding known property.
This will not work for intermediate variables assigned from a property of an indexer.
/cc @CSchulz

no-useless-predicate: treat index signature as optional

---

baselines/packages/mimir/test/no-useless-predicate/default/test.ts.lint
baselines/packages/mimir/test/no-useless-predicate/pre320/test.ts.lint
packages/mimir/src/rules/no-useless-predicate.ts

 no-useless-predicate: fix 'typeof {} === "object"'

---

baselines/packages/mimir/test/no-inferred-empty-object/330/js.js.lint
baselines/packages/mimir/test/no-inferred-empty-object/330/jsx.tsx.lint
baselines/packages/mimir/test/no-inferred-empty-object/330/test.ts.lint
baselines/packages/mimir/test/no-inferred-empty-object/default/test.ts.lint
baselines/packages/mimir/test/no-inferred-empty-object/pre330/js.js.lint
baselines/packages/mimir/test/no-inferred-empty-object/pre330/jsx.tsx.lint
baselines/packages/mimir/test/no-inferred-empty-object/pre330/test.ts.lint
package.json
packages/mimir/src/rules/no-inferred-empty-object.ts
packages/mimir/test/no-inferred-empty-object/330.test.json
packages/mimir/test/no-inferred-empty-object/default.test.json
packages/mimir/test/no-inferred-empty-object/pre330.test.json
packages/mimir/test/no-inferred-empty-object/test.ts
yarn.lock

* fixed a crash when calling `pipe`-like functions
* collect type parameters from inferred signatures
* avoid printing call signature if all type parameters have a default
* added additional tests for function  type unification

no-inferred-empty-object: handle higher order function type inference

---

baselines/packages/wotan/api/src/linter.d.ts
baselines/packages/ymir/api/src/index.d.ts
docs/writing-rules.md
packages/bifrost/src/index.ts
packages/bifrost/test/rule.spec.ts
packages/mimir/src/rules/no-duplicate-case.ts
packages/mimir/src/rules/no-useless-assertion.ts
packages/mimir/src/rules/no-useless-initializer.ts
packages/mimir/src/rules/no-useless-predicate.ts
packages/mimir/src/rules/no-useless-strict.ts
packages/mimir/src/rules/prefer-for-of.ts
packages/mimir/src/rules/typecheck.ts
packages/wotan/language-service/index.ts
packages/wotan/src/linter.ts
packages/wotan/src/project-host.ts
packages/wotan/src/runner.ts
packages/wotan/test/linter.spec.ts
packages/ymir/src/index.ts

After fixing the Program is not updated immediately. Instead this is done just in time on the first access.
That means fixing a Program with only syntactic rules enabled never updates the Program.
To avoid accessing CompilerOptions via Program there is now a new property on RuleContext.

Lazy update of Program

---

.circleci/config.yml
tsconfig-base.json

EOL of Node.js v6 is at the end of the month and some dependencies already start dropping support for it.

Drop node6

---

baselines/packages/mimir/test/no-uninferred-type-parameter/330/test.ts.lint
baselines/packages/mimir/test/no-uninferred-type-parameter/340/test.ts.lint
baselines/packages/mimir/test/no-uninferred-type-parameter/default/test.ts.lint
baselines/packages/mimir/test/no-uninferred-type-parameter/pre330/test.ts.lint
packages/mimir/src/rules/no-uninferred-type-parameter.ts
packages/mimir/test/no-uninferred-type-parameter/test.ts

no-uninferred-type-parameter: handle higher order constructor inference

---

baselines/packages/mimir/test/delete-only-optional-property/default/test.ts.lint
baselines/packages/mimir/test/no-duplicate-spread-property/320/test.ts.lint
baselines/packages/mimir/test/no-duplicate-spread-property/default/test.ts.lint
baselines/packages/mimir/test/no-duplicate-spread-property/loose/test.ts.lint
baselines/packages/mimir/test/no-unstable-api-use/default/test.ts.lint
baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/loose/type-assertion.ts.lint
baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.fix
baselines/packages/mimir/test/no-useless-assertion/strict/type-assertion.ts.lint
packages/mimir/package.json
packages/mimir/src/rules/async-function-assignability.ts
packages/mimir/src/rules/no-duplicate-spread-property.ts
packages/mimir/src/rules/no-restricted-property-access.ts
packages/mimir/src/rules/no-unstable-api-use.ts
packages/mimir/src/rules/no-useless-assertion.ts
packages/mimir/src/rules/no-useless-initializer.ts
packages/mimir/src/rules/no-useless-predicate.ts
packages/mimir/src/rules/no-useless-try-catch.ts
packages/mimir/src/utils.ts
packages/mimir/test/no-duplicate-spread-property/320.test.json
packages/mimir/test/no-duplicate-spread-property/test.ts
packages/mimir/test/no-useless-assertion/type-assertion.ts
yarn.lock

Moves some utility functions to tsutils.
Results in better checking of late bound symbol property names and better display names for computed properties.

update tsutils to latest version

---

.travis.yml
package.json
packages/wotan/package.json
scripts/cleanup-tests.ts
scripts/github-release.ts
scripts/nightly.ts
scripts/prepare-release.ts
scripts/release.ts
scripts/updated.ts
scripts/util.ts
yarn.lock

* now allows patch and prereleases
* patch and prereleases (except 'rc') don't need to happen on master
* fixed some weird conditions
* don't publish prereleases as 'latest' and 'next' to npm
* no longer use the most recent changelog for github releases if it doesn't match

refactor release process

---

baselines/packages/mimir/test/no-restricted-property-access/default/test.ts.lint
packages/mimir/docs/no-restricted-property-access.md
packages/mimir/package.json
packages/mimir/src/rules/no-restricted-property-access.ts
packages/mimir/test/no-restricted-property-access/test.ts
packages/mimir/test/no-restricted-property-access/tsconfig.json
yarn.lock

* allow accessing all members via static 'super'
* allow accessing accessors via 'super'
* allow accessing abstract accessors via 'this' in constructor
* treat MethodSignature like MethodDeclaration
* fix lookup of 'this' container for decorators and computed property names

enhancements for no-restricted-property-access

---

packages/mimir/src/rules/async-function-assignability.ts
packages/mimir/src/rules/await-async-result.ts
packages/mimir/src/rules/await-only-promise.ts
packages/mimir/src/rules/delete-only-optional-property.ts
packages/mimir/src/rules/generator-require-yield.ts
packages/mimir/src/rules/new-parens.ts
packages/mimir/src/rules/no-debugger.ts
packages/mimir/src/rules/no-nan-compare.ts
packages/mimir/src/rules/no-octal-escape.ts
packages/mimir/src/rules/no-return-await.ts
packages/mimir/src/rules/no-unsafe-finally.ts
packages/mimir/src/rules/no-useless-initializer.ts
packages/mimir/src/rules/no-useless-jump-label.ts
packages/mimir/src/rules/no-useless-spread.ts
packages/mimir/src/rules/no-useless-strict.ts
packages/mimir/src/rules/prefer-number-methods.ts
packages/mimir/src/rules/prefer-object-spread.ts
packages/mimir/src/rules/type-assertion.ts
packages/mimir/src/utils.ts
packages/wotan/src/linter.ts
packages/wotan/src/services/default/line-switches.ts

Avoid excessive stack depth in `async-function-assignability` and `generator-require-yield` on very deep AST structures.
This should also increase performance by avoiding recursion where possible.

Optimize usage of WrappedAst

---

baselines/packages/wotan/api/language-service/index.d.ts
packages/mithotyn/README.md
packages/mithotyn/index.ts
packages/wotan/language-service/index.ts

Adds code actions to the language service plugin.
Requires a new release of the VSCode plugin with the new version of `@fimbul/mithotyn` after the next release.

ls plugin: add support for code fixes
